# Generated by Django 5.1.5 on 2025-02-03 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Produktname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis')),
                ('category', models.CharField(choices=[('station', 'Ladestation'), ('cable', 'Ladezubehör'), ('rfid', 'RFID-Lösung')], max_length=20, verbose_name='Kategorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_name', models.CharField(max_length=255, verbose_name='Rechnungsname')),
                ('billing_address', models.TextField(verbose_name='Rechnungsadresse')),
                ('billing_zip_city', models.CharField(max_length=255, verbose_name='PLZ / Ort')),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('billing_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('same_as_billing', models.BooleanField(default=True, verbose_name='Lieferadresse entspricht Rechnungsadresse')),
                ('shipping_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Liefername')),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='Lieferadresse')),
                ('shipping_zip_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='PLZ / Ort (Lieferung)')),
                ('parking_spot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stellplatznummer')),
                ('signature', models.TextField(blank=True, null=True, verbose_name='Unterschrift')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Bestelldatum')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('confirmed', 'Bestätigt'), ('shipped', 'Versandt'), ('delivered', 'Geliefert')], default='pending', max_length=20, verbose_name='Bestellstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Bestellung')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.product', verbose_name='Produkt')),
            ],
        ),
    ]
