services:
  db:
    image: postgres:15
    container_name: charge_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: charge_django
    command: python manage.py runserver 0.0.0.0:8000       # Dev server
    volumes:
      - ./backend/src:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pg_data:

networks:
  backend:
